name: "Build & Test project: some-utils"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'some-utils/**'
      - '!**/README*.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'some-utils/**'
      - '!**/README*.md'

permissions:
  contents: read

jobs:
  build:
    env:
      project_dir: some-utils
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
          build-root-directory: ${{ env.project_dir }}
